"files": [
  {
    "source": "localization.json",                                       #source files filter
    "translation": "localization_%locale%_crowdin.json"        #where translations are stored
  }
]