name: Crowdin Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  Synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Crowdin sync
      uses: crowdin/github-action@1.4.7
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        localization_branch_name: 'l10n_main'
        create_pull_request: true
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    - name: Find Pull Request
      uses: juliangruber/find-pull-request-action@v1.5.0
      id: find-pull-request
      with:
        branch: 'l10n_main'

    - run: echo "Pull Request ${number} (${sha})"
      env:
        number: ${{ steps.find-pull-request.outputs.number }}
        sha: ${{ steps.find-pull-request.outputs.head-sha }}

    - name: Merge Pull Request
      if: ${{ steps.find-pull-request.outputs.number }}
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}
        method: squash
