name: Merge Crowdin PR on new translations

on:
  pull_request:
    types: [opened, synchronize]
    branches:    
      - 'app-ticketing'
  workflow_dispatch:      

jobs:
  merge-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: app-ticketing
      - run: echo "Pull Request ${number} (${sha})"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}